fos_rest:
  format_listener:
    rules:
      - { path: ^/, fallback_format: json, priorities: [ 'json' ] }

  exception:
    enabled: true
    exception_controller: 'Acme\DemoBundle\Controller\ExceptionController::showAction'

  view:
    view_response_listener:  'force'
    formats:
      json: true